### ISSUE TITLE
canvas DOM element is appending on every toCanvas call

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/ethereum-qr-code#15]
Your .toCanvas do `parentEl.appendChild(canvas);` on every call.
https://github.com/jibrelnetwork/ethereum-qr-code/blob/master/src/ethereumQrPlugin.js#L44
I think it is not cool idea.
Because some UI can allows users call this method many times.
For example:
* user entered amount/address
* UI draws canvas
* user re-entered amount/address
* UI re-draws canvas
Istead of it, now it will draw canvas on each user input.

**Comment by shershen08** [comment]
Plugin goal is just generating the address and QR code. The way parent application uses it is up to developer.
If you mean to have smth like throttle / debounce logic - I suggest that it should be in the parent application, it I the plugin.

**Comment by IViol** [comment]
I understand, but in this case user of the library must not only use API, but manage DOM.
I recommend you to implement some logic of remove/removeChild/replaceChild.
