### ISSUE TITLE
[documentation] undef `codeContainer`

### ISSUE THREAD

**Issue by mesqueeb** [jibrelnetwork/ethereum-qr-code#24]
I'm trying to implement your plugin, but right from the start of the docs you write:
`new EthereumQRPlugin(codeContainer);`
However, this `codeContainer` is undefined, so I'm very confused what to feed in there...

```js
import EthereumQRPlugin from 'ethereum-qr-code';

// later in code
const qr = new EthereumQRPlugin(codeContainer);
const qrCode = qr.toCanvas({
    selector: '#my-qr-code',
    to,
    gas
});
```

**Comment by IViol** [comment]
Hey dude

`EthereumQRPlugin` doesn't require any constructor parameters.
README.md was updated.

**Comment by mesqueeb** [comment]
awesome! Thanks!!!
