### ISSUE TITLE
[Usage] Docs differ from Demo

### ISSUE THREAD

**Issue by mesqueeb** [jibrelnetwork/ethereum-qr-code#25]
in the [demo](https://jibrelnetwork.github.io/ethereum-qr-code/demo-simple.html) you initialise with 2 objects in toCanvas:
```js
//run the plugin
qr.toCanvas(sendDetails, configDetails)
```
but in the main docs you put the selector in the same object as the `sendDetails` in the demo: 
```js
const qrCode = qr.toCanvas({
    selector: '#my-qr-code',
    to,
    gas
})
```
Which one is correct?

**Comment by IViol** [comment]
First one is correct. README updated.
