### ISSUE TITLE
Price doesn't get filled in the Trust wallet / Cipher wallet apps.

### ISSUE THREAD

**Issue by mesqueeb** [jibrelnetwork/ethereum-qr-code#27]
When scanning the QR in the Trust wallet & Cipher wallet apps, the price field is not filled in.

**Comment by mesqueeb** [comment]
After research this seems to be an issue where this library uses `"value"` and most wallets only support `"amount"`.

Could you create the possibility to use `"amount"` in the QR code instead?

**Comment by mesqueeb** [comment]
Actual usage of the QR protocol is currently **very fractured** and gives different and unexpected results based on which wallet the user uses.

Some problems we have found with some Ethereum wallets:

- *imToken*, *BRD wallet*, *Lykke* require a QR field: `amount` to be `ETH`

- *Trust wallet* requires a QR field: `amount` to be `wei` instead of ETH!

- *Toshi wallet* crashes on QR code scan (at time of writing 2018-07-24)

- None of the wallets we tried use the `value` field...

For now I have forked the package [here](https://github.com/DRI-network/ethereum-qr-code) and changed the field called `value` to `amount`. If there would be an update in the future to have an option to also support the `amount` field next to the `value` field, that would be great!

**Comment by CKKwan** [comment]
Seriously I can't find any wallet that can support more than the address and amount field in QR code.

Sending Token is impossible.

Hope someone can shed some light on this issue. TIA

**Comment by stcherenkov** [comment]
Yeah, there is no source of truth for QR code links, so there is no way to implement proper price field for multiple wallets. Looks like the industry needs someone to stand up, create a standard and gather as many companies around it as possible. Until that – I don't think we can do much.
